version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bijak_solat_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - bijak_solat

  nginx:
    image: nginx:alpine
    container_name: bijak_solat_nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    networks:
      - bijak_solat

  db:
    image: mysql:8.0
    container_name: bijak_solat_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - bijak_solat

networks:
  bijak_solat:
    driver: bridge

volumes:
  dbdata:
